### EXAMPLE DOCKER COMPOSE ###
services:
  audiobookshelf:
    build:
      context: .
      dockerfile: Dockerfile
    # ABS runs on port 80 internally within this Go Docker setup.
    # We map port 13378 on the host to port 80 in the container.
    ports:
      - 13378:80
    volumes:
      # These volumes keep your library persistent and allow media to be accessed by the ABS server.
      # The path to the left of the colon is the path on your computer,
      # and the path to the right of the colon is where the data is available to ABS in Docker.
      - ./audiobooks:/audiobooks
      - ./podcasts:/podcasts
      # The metadata directory can be stored anywhere on your computer
      - ./metadata:/metadata
      # The config directory needs to be on the same physical machine you are running ABS on
      - ./config:/config
    restart: unless-stopped
