package hls

import (
	"bytes"
	"context"
	"database/sql"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"audiobookshelf/internal/core"
	_ "modernc.org/sqlite"
)

func setupIntegrationDB(t *testing.T) *sql.DB {
	db, err := sql.Open("sqlite", ":memory:")
	if err != nil {
		t.Fatalf("Failed to open database: %v", err)
	}

	queries := []string{
		`CREATE TABLE libraryItems (id TEXT PRIMARY KEY, mediaId TEXT, mediaType TEXT, libraryId TEXT)`,
		`CREATE TABLE books (id TEXT PRIMARY KEY, title TEXT, audioFiles TEXT)`,
		`CREATE TABLE playbackSessions (id TEXT PRIMARY KEY, userId TEXT, mediaItemId TEXT, mediaItemType TEXT, startTime REAL, libraryId TEXT, extraData TEXT, createdAt TEXT, updatedAt TEXT)`,
		`CREATE TABLE authors (id TEXT PRIMARY KEY, name TEXT)`,
		`CREATE TABLE bookAuthors (bookId TEXT, authorId TEXT)`,
		`CREATE TABLE libraryFolders (id TEXT PRIMARY KEY, path TEXT, libraryId TEXT)`,
	}

	for _, q := range queries {
		if _, err := db.Exec(q); err != nil {
			t.Fatalf("Failed to execute query %q: %v", q, err)
		}
	}

	return db
}

func TestHLS_PlayAndServeFlow(t *testing.T) {
	db := setupIntegrationDB(t)
	defer db.Close()

	// 1. Seed the DB
	_, err := db.Exec(`INSERT INTO libraryItems (id, mediaId, mediaType, libraryId) VALUES ('item-1', 'book-1', 'book', 'lib-1')`)
	if err != nil {
		t.Fatalf("seed libraryItem failed: %v", err)
	}

	audioFilesJSON := `[
		{"index":0, "exclude":false, "duration":120.0, "codec":"mp3", "mimeType":"audio/mpeg", "metadata":{"path":"/fake/path.mp3", "filename":"path.mp3", "size":1000}}
	]`
	_, err = db.Exec(`INSERT INTO books (id, title, audioFiles) VALUES ('book-1', 'Test Book Title', ?)`, audioFilesJSON)
	if err != nil {
		t.Fatalf("seed book failed: %v", err)
	}

	_, err = db.Exec(`INSERT INTO authors (id, name) VALUES ('author-1', 'Test Author')`)
	if err != nil {
		t.Fatalf("seed author failed: %v", err)
	}

	_, err = db.Exec(`INSERT INTO bookAuthors (bookId, authorId) VALUES ('book-1', 'author-1')`)
	if err != nil {
		t.Fatalf("seed bookAuthor failed: %v", err)
	}

	_, err = db.Exec(`INSERT INTO libraryFolders (id, path, libraryId) VALUES ('folder-1', '/fake', 'lib-1')`)
	if err != nil {
		t.Fatalf("seed libraryFolder failed: %v", err)
	}

	// 2. Initialize StreamManager
	sm := NewStreamManager()
	defer sm.Close()

	tempDir := t.TempDir()

	// 3. Test HandlePlayItem (Session Creation)
	userSess := &core.UserSession{
		ID:       "user-1",
		Username: "testuser",
		Type:     "user",
		IsActive: true,
	}

	playHandler := HandlePlayItem(db, sm)

	bodyBytes := []byte(`{"startTime": 10.0}`)
	req := httptest.NewRequest("POST", "/api/items/item-1/play", bytes.NewBuffer(bodyBytes))
	req = req.WithContext(context.WithValue(req.Context(), core.UserContextKey, userSess))
	rr := httptest.NewRecorder()

	playHandler.ServeHTTP(rr, req)

	if rr.Code != http.StatusOK {
		t.Fatalf("HandlePlayItem returned code %d, body: %s", rr.Code, rr.Body.String())
	}

	var playResp map[string]interface{}
	if err := json.Unmarshal(rr.Body.Bytes(), &playResp); err != nil {
		t.Fatalf("failed to decode response: %v", err)
	}

	sessionID, ok := playResp["id"].(string)
	if !ok || sessionID == "" {
		t.Fatalf("response missing session ID: %v", playResp)
	}

	if playResp["displayTitle"] != "Test Book Title" {
		t.Errorf("expected displayTitle 'Test Book Title', got %v", playResp["displayTitle"])
	}
	if playResp["displayAuthor"] != "Test Author" {
		t.Errorf("expected displayAuthor 'Test Author', got %v", playResp["displayAuthor"])
	}

	audioTracks, ok := playResp["audioTracks"].([]interface{})
	if !ok || len(audioTracks) != 1 {
		t.Fatalf("expected 1 audio track, got %v", playResp["audioTracks"])
	}

	track := audioTracks[0].(map[string]interface{})
	if track["index"].(float64) != 0 {
		t.Errorf("expected track index 0, got %v", track["index"])
	}
	if track["duration"].(float64) != 120.0 {
		t.Errorf("expected track duration 120.0, got %v", track["duration"])
	}

	// 4. Seed a stream directly in the StreamManager for ServeHLS testing
	// We want to simulate the files generated by ffmpeg
	streamPath := filepath.Join(tempDir, "streams", sessionID)
	err = os.MkdirAll(streamPath, 0755)
	if err != nil {
		t.Fatalf("failed to create stream dir: %v", err)
	}

	playlistContent := GetPlaylistStr("output", 120.0, 6.0, "mpegts")
	err = os.WriteFile(filepath.Join(streamPath, "output.m3u8"), []byte(playlistContent), 0644)
	if err != nil {
		t.Fatalf("failed to write output.m3u8: %v", err)
	}

	err = os.WriteFile(filepath.Join(streamPath, "output-0.ts"), []byte("ts content segment 0"), 0644)
	if err != nil {
		t.Fatalf("failed to write output-0.ts: %v", err)
	}

	// We load the stream to stream manager so the mock serves it
	stream, err := sm.LoadOrCreateStream(db, sessionID, tempDir, nil)
	if err != nil {
		// If transcoding starts, it might fail if ffmpeg is missing, but here we can mock it
		// because stream exists on disk (output.m3u8 is present). Let's see if LoadOrCreateStream returns the stream.
		if !strings.Contains(err.Error(), "exec") && !strings.Contains(err.Error(), "failed to start transcode") {
			t.Fatalf("LoadOrCreateStream failed: %v", err)
		}
	}

	// Double check if stream is loaded
	if stream == nil {
		stream = &Stream{
			ID:                sessionID,
			UserID:            "user-1",
			LibraryItemID:     "item-1",
			SegmentLength:     6.0,
			StreamPath:        streamPath,
			ConcatFilesPath:   filepath.Join(streamPath, "files.txt"),
			PlaylistPath:      filepath.Join(streamPath, "output.m3u8"),
			FinalPlaylistPath: filepath.Join(streamPath, "final-output.m3u8"),
			SegmentsCreated:   make(map[int]bool),
			Tracks:            []Track{{Index: 0, Duration: 120.0, Path: "/fake/path.mp3"}},
		}
		sm.AddStream(stream)
	}

	// 5. Test ServeHLS
	hlsHandler := ServeHLS(db, tempDir, sm, nil)

	// Test 5a: Serving output.m3u8 with authorization token query param
	req = httptest.NewRequest("GET", "/hls/"+sessionID+"/output.m3u8?token=testtoken", nil)
	req = req.WithContext(context.WithValue(req.Context(), core.UserContextKey, userSess))
	rr = httptest.NewRecorder()

	hlsHandler.ServeHTTP(rr, req)

	if rr.Code != http.StatusOK {
		t.Fatalf("ServeHLS output.m3u8 returned code %d, body: %s", rr.Code, rr.Body.String())
	}

	body := rr.Body.String()
	if !strings.Contains(body, "#EXTM3U") {
		t.Errorf("Expected M3U8 headers, got: %s", body)
	}
	if !strings.Contains(body, "output-0.ts?token=testtoken") && !strings.Contains(body, "output0.ts?token=testtoken") {
		t.Errorf("Expected token appended to TS segments in playlist, got: %s", body)
	}

	// Test 5b: Serving output-0.ts
	req = httptest.NewRequest("GET", "/hls/"+sessionID+"/output-0.ts?token=testtoken", nil)
	req = req.WithContext(context.WithValue(req.Context(), core.UserContextKey, userSess))
	rr = httptest.NewRecorder()

	hlsHandler.ServeHTTP(rr, req)

	if rr.Code != http.StatusOK {
		t.Fatalf("ServeHLS output-0.ts returned code %d, body: %s", rr.Code, rr.Body.String())
	}
	if rr.Body.String() != "ts content segment 0" {
		t.Errorf("Expected 'ts content segment 0', got %q", rr.Body.String())
	}

	// Test 5c: Access by another user (Forbidden)
	otherUserSess := &core.UserSession{
		ID:       "user-2",
		Username: "otheruser",
		Type:     "user",
		IsActive: true,
	}
	req = httptest.NewRequest("GET", "/hls/"+sessionID+"/output.m3u8", nil)
	req = req.WithContext(context.WithValue(req.Context(), core.UserContextKey, otherUserSess))
	rr = httptest.NewRecorder()

	hlsHandler.ServeHTTP(rr, req)

	if rr.Code != http.StatusForbidden {
		t.Errorf("Expected 403 Forbidden for different user, got %d", rr.Code)
	}

	// Test 5d: Access by admin (Allowed)
	adminUserSess := &core.UserSession{
		ID:       "user-admin",
		Username: "adminuser",
		Type:     "admin",
		IsActive: true,
	}
	req = httptest.NewRequest("GET", "/hls/"+sessionID+"/output-0.ts", nil)
	req = req.WithContext(context.WithValue(req.Context(), core.UserContextKey, adminUserSess))
	rr = httptest.NewRecorder()

	hlsHandler.ServeHTTP(rr, req)

	if rr.Code != http.StatusOK {
		t.Errorf("Expected 200 OK for admin, got %d", rr.Code)
	}
}
